
public enum DefinedAct{
	ACT_SHOW_START,
	ACT_CROSSING_TO_SCHOOL,
	ACT_ARRIVE_AT_SCHOOL,
	ACT_DUANJUN,
	ACT_RED_BUILDING,
	ACT_304,
	ACT_INSIDE_DOOR,
	ACT_DORM,
	ACT_ELEVATOR,
	ACT_BAI_ROOM,
	ACT_YU_PINGFAN,
	ACT_GUANXINTAI,
	ACT_ROOFTOP
}